### ISSUE TITLE
Windows Version

### ISSUE THREAD

**Issue by smiler96** [vicoslab/mixed-segdec-net-comind2021#3]
Thanks for your great work!
can you provide a light version on windows system?

**Comment by skokec** [comment]
Hi, since the code is written in Python and uses PyTorch it should be possible to run on Windows, however, we have not tested it and cannot guarantee it to work. You will also need to write your own scripts for running the experiments based on the provided bash .sh scripts.

Alternatively, you can try running the provided code on Windows Subsystem for Linux using experimental [CUDA drivers for WSL](https://docs.nvidia.com/cuda/wsl-user-guide/index.html), which would in theory enable to use the provided code on windows without any modifications.

**Comment by smiler96** [comment]
> Hi, since the code is written in Python and uses PyTorch it should be possible to run on Windows, however, we have not tested it and cannot guarantee it to work. You will also need to write your own scripts for running the experiments based on the provided bash .sh scripts.
> 
> Alternatively, you can try running the provided code on Windows Subsystem for Linux using experimental [CUDA drivers for WSL](https://docs.nvidia.com/cuda/wsl-user-guide/index.html), which would in theory enable to use the provided code on windows without any modifications.

Thanks, i have made it to run on Windows.
